# Generated by Django 5.0.4 on 2026-03-12 13:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Brand Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tagline',
            field=models.CharField(default='The Ultimate Supercar Encyclopedia', max_length=255),
        ),
        migrations.CreateModel(
            name='BrandPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('country_of_origin', models.CharField(choices=[('Italy', 'Italy'), ('Germany', 'Germany'), ('UK', 'United Kingdom'), ('USA', 'United States'), ('Sweden', 'Sweden'), ('France', 'France'), ('Czech Republic', 'Czech Republic')], max_length=100)),
                ('founded_year', models.PositiveIntegerField()),
                ('headquarters', models.CharField(max_length=255)),
                ('origin_story', wagtail.fields.RichTextField()),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('brand_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Brand Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CarModelPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('year_of_manufacture', models.PositiveIntegerField()),
                ('country_of_origin', models.CharField(max_length=100)),
                ('engine_type', models.CharField(choices=[('V6', 'V6'), ('V8', 'V8'), ('V10', 'V10'), ('V12', 'V12'), ('W12', 'W12'), ('W16', 'W16'), ('Flat-6', 'Flat-6 (Boxer)'), ('Inline-6', 'Inline-6'), ('Straight-8', 'Straight-8')], max_length=20)),
                ('horsepower', models.PositiveIntegerField(help_text='in bhp')),
                ('units_produced', models.PositiveIntegerField(blank=True, help_text='Total units produced worldwide (leave blank if unlimited/ongoing)', null=True)),
                ('is_limited_edition', models.BooleanField(default=False)),
                ('top_speed_kmh', models.PositiveIntegerField(blank=True, help_text='Top speed in km/h', null=True)),
                ('zero_to_hundred', models.DecimalField(blank=True, decimal_places=2, help_text='0-100 km/h in seconds', max_digits=4, null=True)),
                ('description', wagtail.fields.RichTextField()),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Car Model Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
